### ISSUE TITLE
Is kickoff count as a freekick?

### ISSUE THREAD

**Issue by mahi97** [RoboCup-SSL/ssl-rules#1]
Rules say that:

> 8.1.2. Lack Of Progress
> There is a lack of progress if only one team is allowed to manipulate the ball (kick-off, direct free kick, indirect free kick, penalty kick) and does not bring the ball into play in time. The time limit is 5 seconds for **free kicks** in division A and 10 seconds in **all other cases**.

Is it means that the time limit for kickoff is 10 sec?

**Comment by pardinensis** [comment]
The 5 seconds only apply to direct free kicks and indirect free kicks in division A. Since a kick-off (or penalty kick) is not a free kick, you've got a time window of 10 seconds to bring the ball into play.

I will rephrase it a little to hopefully make it more clear. Thanks for the feedback :)
