### ISSUE TITLE
Duplicated game event table

### ISSUE THREAD

**Issue by kkimurak** [RoboCup-SSL/ssl-rules#37]
In the work of #35, some duplicates in the game event table were overlooked and merged into the master.
e.g. 

* There are two "Events for scoring goals" table
  Difference : for "Possible Goal" event, action for one is "Stop → Kick-Off" and the other is "Halt"
  * [html 1](https://robocup-ssl.github.io/ssl-rules/sslrules.html#_events_for_scoring_goals) and  [source 1](https://github.com/RoboCup-SSL/ssl-rules/commit/d8363652f5000cc6b2ea11000ea73875c2069ba5#diff-220f691b4315250e9d3d91b926fb2881R22-R29)
  * [html 2](https://robocup-ssl.github.io/ssl-rules/sslrules.html#_events_for_scoring_goals_2) and [source 2](https://github.com/RoboCup-SSL/ssl-rules/commit/d8363652f5000cc6b2ea11000ea73875c2069ba5#diff-220f691b4315250e9d3d91b926fb2881R96-R103)
* There are two "Unsporting Behavior" event, in "Events for Offenses" table and in "Other events" table
  * [html 1](https://robocup-ssl.github.io/ssl-rules/sslrules.html#_events_for_offenses) and [source 1](https://github.com/RoboCup-SSL/ssl-rules/commit/d8363652f5000cc6b2ea11000ea73875c2069ba5#diff-220f691b4315250e9d3d91b926fb2881R38)
  * [html 2](https://robocup-ssl.github.io/ssl-rules/sslrules.html#_other_events) and [source 2](https://github.com/RoboCup-SSL/ssl-rules/commit/d8363652f5000cc6b2ea11000ea73875c2069ba5#diff-220f691b4315250e9d3d91b926fb2881R123)

* There are two "Double touch" event, in "Events for Offenses" table and in "Other events" table
  * [html 1](https://robocup-ssl.github.io/ssl-rules/sslrules.html#_events_for_offenses) and [source 1](https://github.com/RoboCup-SSL/ssl-rules/commit/d8363652f5000cc6b2ea11000ea73875c2069ba5#diff-220f691b4315250e9d3d91b926fb2881R37)
  * [html 2](https://robocup-ssl.github.io/ssl-rules/sslrules.html#_other_events) and [source 2](https://github.com/RoboCup-SSL/ssl-rules/commit/d8363652f5000cc6b2ea11000ea73875c2069ba5#diff-220f691b4315250e9d3d91b926fb2881R111)

and so on. Most of duplication is caused by "Other events" table, so I think we need to check them again.

**Comment by g3force** [comment]
thx for pointing this out. The two sections should have been removed. Might have been a merge issue...
