### ISSUE TITLE
Clarification of the penalty marks

### ISSUE THREAD

**Issue by emielsteerneman** [RoboCup-SSL/ssl-rules#53]
The current wording of the penalty marks has caused confusion within our team, and problems during the match in the RoboCup 2022. The penalty marks are defined as follows :

```
For each field half the penalty mark is on the mid-line (not halfway line), 8 meters (division A) or 6 meters (division B) away from the opponent goal center.
```

It is clear where the two penalty marks are on each half (8 meters from each goal center), but to whom each penalty mark belongs is ambiguous. Intuition tells me that penalties are taken from the penalty mark closest to the opponent's goal, mainly because this is the case in human soccer. This is however not the case.

I'd like to suggest a clarification of the penalty mark from which to take a penalty :

```
For each field half, the penalty mark is on the mid-line (not halfway line), 8 meters (division A) or 6 meters (division B) away from the opponent's goal center. 
The team taking the penalty has to start at the penalty mark that is on the midline and 8 meters (division A) or 6 meters (division B) away from the opponent's goal.
```

**Comment by g3force** [comment]
Your suggestions contains redundant wording that I'd like to avoid.

What about this:
```
For each team, the penalty mark is on the <<Additional Lines, mid-line>> (not halfway line), 8 meters (division A) or 6 meters (division B) away from the opponent's goal center.
```

Instead of defining it per field half (which is part of the confusing), define it per team.

**Comment by emielsteerneman** [comment]
Unfortunately, this sentence contains the same problem that the original sentence has. It clearly defines where the penalty marks are, but it is unclear from what penalty mark to start a penalty. 

With this suggestion, I know that my team's penalty mark is 8 meters away from the opponent's goal center, but I don't know what "my team's penalty mark" means. Does that mean that I defend against that penalty mark, or that I start a penalty from that mark?

**Comment by g3force** [comment]
I see, what you mean... I thought it would be sufficient to relate the point to the goal on which to be played against (opposed to locating the point on a field half), but I agree this is still too implicit.

How about this:
```
The penalty mark defines the point from which a team executes a penalty kick against the opponent goal. It is located on the <<Additional Lines, mid-line>> (not halfway line) and 8 meters (division A) or 6 meters (division B) away from the opponent's goal center.
```

**Comment by emielsteerneman** [comment]
Yes, I think that this suggestion is good! It solves the problem I described, and I feel that it is also an improvement over my original suggestion.

**Comment by g3force** [comment]
Merged.
