### ISSUE TITLE
Penalty keeper start position

### ISSUE THREAD

**Issue by JornJorn** [RoboCup-SSL/ssl-rules#82]
During a penalty kick, in the rules (5.3.5) it says the following

. The defending keeper has to move to the goal line and keep touching it

However the game controller checks if the keeper is on the goal line and between the goal posts, which is also the requirement in human soccer.

I propose changing the wording of the rule such that it is clear the keeper must stay between the goalposts.

**Comment by g3force** [comment]
I've created a PR for this: https://github.com/RoboCup-SSL/ssl-rules/pull/83/files
